Controllers/ConcertController.cs
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SoundSphere.Helpers;
using SoundSphere.Interfaces;
using SoundSphere.Models;
using SoundSphere.ViewModels;
using Tutorial;

namespace SoundSphere.Controllers;

public class ConcertController : Controller {

    private readonly IConcertRepository _concertRepository;
    private readonly IPhotoRepository _photoRepository;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public ConcertController(
        IConcertRepository concertRepository,
        IPhotoRepository photoRepository,
        IHttpContextAccessor httpContextAccessor
    ) {
        _concertRepository = concertRepository;
        _photoRepository = photoRepository;
        _httpContextAccessor = httpContextAccessor;
    }

    public async Task<IActionResult> Index() {
        IEnumerable<MusicConcert> concerts = await _concertRepository.GetAllConcerts();
        return View(concerts);
    }

    public async Task<IActionResult> Detail(int id) {
        MusicConcert searched_concert = await _concertRepository.GetConcertById(id);
        return View(searched_concert);
    }

    public IActionResult Create() {
        var currenUserId = _httpContextAccessor.HttpContext.User.GetUserId();
        var createConcertVM = new CreateConcertVM { AppUserId = currenUserId };
        return View(createConcertVM);
    }

    [HttpPost]
    public async Task<IActionResult> Create(CreateConcertVM concertVM) {
        if (ModelState.IsValid) {
            var result = await _photoRepository.AddPhotoAsync(concertVM.Image);
            if (result.Error == null) {
                var concert = new MusicConcert {
                    Name = concertVM.Name,
                    Artist = concertVM.Artist,
                    Venue = concertVM.Venue,
                    Image = result.Url.ToString(),
                    AppUserId = concertVM.AppUserId,
                    Description = concertVM.Description,
                    Rating = new Rating {
                        Comment = concertVM.Rating.Comment,
                        Points = concertVM.Rating.Points,
                    }
                };
                _concertRepository.AddNewConcert(concert);
                return RedirectToAction("Index");
            }
            else {
                ModelState.AddModelError(
                    "", 
                    $"Photo upload failed: {result.Error.Message}"
                );
            }
        }
        return View(concertVM);
    }

    public async Task<IActionResult> Edit(int id) {
        var concert = await _concertRepository.GetConcertById(id);
        if (concert == null) {
            return View("Error");
        }

        var concertVM = new EditConcertVM {
            Name = concert.Name,
            Artist = concert.Artist,
            URL = concert.Image,
            Venue = concert.Venue,
            Description = concert.Description,
            RatingId = concert.RatingId,
            Rating = concert.Rating
        };
        return View(concertVM);

    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, EditConcertVM concertVM) {
        if (!ModelState.IsValid) {
            ModelState.AddModelError("", "Failed to edit club");
            return View("Edit", concertVM);
        }

        var userConcert = await _concertRepository.GetConcertByIdAsyncNoTracking(id);
        if (userConcert != null) {
            try {
                await _photoRepository.DeletePhotoAsync(userConcert.Image);
            }
            catch (Exception ex) {
                ModelState.AddModelError("", "Cannot delete photo");
                return View(concertVM);
            }

            var photoResult = await _photoRepository.AddPhotoAsync(concertVM.Image);
            var concert = new MusicConcert {
                Id = id,
                Name = concertVM.Name,
                Artist = concertVM.Artist,
                Venue = concertVM.Venue,
                Description = concertVM.Description,
                Image = photoResult.Url.ToString(),
                RatingId = concertVM.RatingId,
                Rating = concertVM.Rating

            };
            _concertRepository.UpdateExistingConcert(concert);
            return RedirectToAction("Index");
        }
        else {
            return View("Error");
        }
    }

    public async Task<IActionResult> Delete(int id) {
        var concertDetails = await _concertRepository.GetConcertById(id);
        if (concertDetails == null) {
            return View("Error");
        }
        return View(concertDetails);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteClub(int id) {
        var concertDetails = await _concertRepository.GetConcertById(id);
        if (concertDetails == null) {
            return View("Error");
        }

        _concertRepository.DeleteConcert(concertDetails);
        return RedirectToAction("Index");
    }
}

Controllers/TrackController.cs
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SoundSphere.Helpers;
using SoundSphere.Interfaces;
using SoundSphere.Models;
using SoundSphere.ViewModels;
using Tutorial;

namespace SoundSphere.Controllers;

public class TrackController : Controller {

    private readonly ITrackRepository _trackRepository;
    private readonly IPhotoRepository _photoRepository;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public TrackController(
        ITrackRepository trackRepository,
        IPhotoRepository photoRepository,
        IHttpContextAccessor httpContextAccessor
    ) {
        _trackRepository = trackRepository;
        _photoRepository = photoRepository;
        _httpContextAccessor = httpContextAccessor;
    }

    public async Task<IActionResult> Index() {
        IEnumerable<MusicTrack> concerts = await _trackRepository.GetAllTracks();
        return View(concerts);
    }

    public async Task<IActionResult> Detail(int id) {
        MusicTrack searched_concert = await _trackRepository.GetTrackById(id);
        return View(searched_concert);
    }

    public IActionResult Create() {
        var currenUserId = _httpContextAccessor.HttpContext.User.GetUserId();
        var createTrackVM = new CreateTrackVM { AppUserId = currenUserId };
        return View(createTrackVM);
    }

    [HttpPost]
    public async Task<IActionResult> Create(CreateTrackVM createTrackVM) {
        if (ModelState.IsValid) {
            var result = await _photoRepository.AddPhotoAsync(createTrackVM.Image);
            if (result.Error == null) {
                var track = new MusicTrack {
                    Title = createTrackVM.Title,
                    Artist = createTrackVM.Artist,
                    Image = result.Url.ToString(),
                    AppUserId = createTrackVM.AppUserId,
                    Genre = createTrackVM.Genre,
                    ReleaseYear = createTrackVM.ReleaseYear,
                    Rating = new Rating
                    {
                        Comment = createTrackVM.Rating.Comment,
                        Points = createTrackVM.Rating.Points,
                    }
                };
                _trackRepository.AddNewTrack(track);
                return RedirectToAction("Index");
            }
            else {
                ModelState.AddModelError("", $"Photo upload failed: {result.Error.Message}");
            }
        }

        return View(createTrackVM);
    }

    public async Task<IActionResult> Edit(int id) {
        var track = await _trackRepository.GetTrackById(id);
        if (track == null) {
            return View("Error");
        }

        var editTrackVM = new EditTrackVM {
            Title = track.Title,
            Artist = track.Artist,
            URL = track.Image,
            Genre = track.Genre,
            ReleaseYear = track.ReleaseYear,
            RatingId = track.RatingId,
            Rating = track.Rating
        };
        return View(editTrackVM);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, EditTrackVM editTrackVM) {
        if (!ModelState.IsValid) {
            ModelState.AddModelError("", "Failed to edit club");
            return View("Edit", editTrackVM);
        }

        var userTrack = await _trackRepository.GetTrackByIdAsyncNoTracking(id);
        if (userTrack != null) { 
            try {
                await _photoRepository.DeletePhotoAsync(userTrack.Image);
            }
            catch (Exception ex) {
                ModelState.AddModelError("", "Cannot delete photo");
                return View(editTrackVM);
            }

            var photoResult = await _photoRepository.AddPhotoAsync(editTrackVM.Image);
            var track = new MusicTrack {
                Id = id,
                Title = editTrackVM.Title,
                Artist = editTrackVM.Artist,
                Genre = editTrackVM.Genre,
                ReleaseYear = editTrackVM.ReleaseYear,
                Image = photoResult.Url.ToString(),
                RatingId = editTrackVM.RatingId,
                Rating = editTrackVM.Rating

            };
            _trackRepository.UpdateExistingTrack(track);
            return RedirectToAction("Index");
        }
        else {
            return View("Error");
        }
    }

    public async Task<IActionResult> Delete(int id) {
        var trackDetails = await _trackRepository.GetTrackById(id);
        if (trackDetails == null) {
            return View("Error");
        }
        return View(trackDetails);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteClub(int id) {
        var trackDetails = await _trackRepository.GetTrackById(id);
        if (trackDetails == null) {
            return View("Error");
        }
        _trackRepository.DeleteTrack(trackDetails);
        return RedirectToAction("Index");
    }
}

Views/Dashboard/Index.cshtml
@model SoundSphere.ViewModels.AppDashboardVM

<h1 class="display-4 fw-normal">User Dashboard</h1>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Track" asp-action="Create">Create Track</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Concert" asp-action="Create">Create Concert</a>
<div class="album py-5 bg-light">
    <div class="container">
        <h2 class="display-4 fw-normal">Your Tracks</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            @foreach (var item in Model.Tracks)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Genre</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Track" asp-action="Detail" asp-route-id="@item.Id"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <a asp-controller="Track" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Track" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.Artist</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <h2 class="display-4 fw-normal">Your Concerts</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (var item in Model.Concerts)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="auto" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Name</p>
                            <p class="card-text">@item.Venue</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Concert" asp-action="Detail" asp-route-id="@item.Id"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                     @if (User.Identity.IsAuthenticated)
                                    {
                                        <a asp-controller="Concert" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Concert" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.Artist</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>